title          : GMT 教學手冊
author         : 鄭懷傑 (Whyjay Zheng)
copyright      : "2016-2022"  
# logo           : images/index_banner_logo.png

html:
  use_edit_page_button: false
  use_repository_button: false
  use_issues_button: false
  baseurl: https://gmt-tutorials.org

# bibtex_bibfiles:
#  - refs.bib

# bibtex_reference_style: author_year

repository:
  url: https://github.com/whyjz/GMT-tutorials
  branch: jb
  path_to_book: docs

# launch_buttons:
#   notebook_interface: "jupyterlab" # The interface interactive links will activate ["classic", "jupyterlab"]
#   binderhub_url: "https://mybinder.org"
#   # thebe: true
  
# execute:
#   execute_notebooks : 'off'
#   timeout           : 30
#   allow_errors      : false

sphinx:
  extra_extensions:
  - sphinx_inline_tabs
  config:
    language: zh_TW
    html_theme_options:
      toc_title: 段落