name: Sphinx Build and Deploy

on: 
  push:
    branches: [sean_build]

jobs:
  pages:
    runs-on: ubuntu-latest
    env:
      TZ: "Asia/Taipei"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: sean_build
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install packages
        run: |
          pip install sphinx sphinx_rtd_theme sphinx-intl
      - name: Build
        run: |
          make html
          make gettext
          sphinx-intl update -p _build/locale -l en
          make -e SPHINXOPTS="-D language='en'" BUILDSURFIX="/en" html
          bash decorate.bash
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_KEY }}
          publish_dir: ./_build/html/
          publish_branch: gh-pages  # deploying branch
